import { Inter } from "next/font/google";
import "./globals.css";
import { ProductsController } from "@/productsController";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Shopping cart test",
  description: "Generated by create next app",
};
// Nota importante.
// Durante la primera compilación de next.js hay un bug con el layout vs los hooks del ProducsController
// Seguramente deba hacerse diferente, por ahora no tuve tiempo de resolverlo
// Se mostrará un mensaje de error que solicita recargar la página
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProductsController>
            {children}
        </ProductsController>
      </body>
    </html>
  );
}
